data/schemes/base16-twilight-dark.json
I'm sure someone will eventually add to base16 builder (maybe after erb-removal refactor), but in the interim, here's my shell scheme of choice
/cc @chriskempson
=> add base16-twilight-dark scheme

po/pt_BR.po
I've made some improvements to the translation to pt_BR, especially for consistency in the use of verbs and some mistakes. Some wording was shamelessly copied from gnome-terminal.
=> Improvements to pt_BR translation

source/gx/gtk/actions.d
=> fix unit test function call

data/schemes/monokai.json
Just adding a new scheme based on the Monokai color scheme - http://www.monokai.nl/blog/2006/07/15/textmate-color-theme/
=> new Monokai scheme

po/pt_BR.po
=>  Translation pt_BR updated

po/terminix.pot, source/gx/terminix/profilewindow.d, source/gx/terminix/terminal/terminal.d
This fixes a few issues with the localization, mainly missing strings and a syntax error in the pot files.
I also experimented with xgettext whether I could get the strings automatically extracted, but so far the results are not so great. I had more luck in the past with a project in a language unsupported by xgettext where I could just reuse the support for a syntactically similar language. I will try a bit more and let you know if I got something working.
Something else: Have you already thought about setting up some translation tool with git integration, something like Transifex or maybe Weblate? This could eliminate all the translation pull requests. Transifex is maybe the easiest one to setup and use, see e.g. https://www.transifex.com/phwolfer/Android_PwdHash/dashboard/ . Weblate is …
=> Localization issue fixes

po/zh_CN.po, po/zh_TW.po
Here is a zh_CN translation for Terminix, and finished.
=> l10n: add zh_{CN,TW} translation, 100%

po/pt_BR.po
=> pt_BR.po - 101%

po/zh_CN.po
=> l10n/zh_CN: keeping up with upstream

po/pt_BR.po
=> pt_BR.po updated #144

po/pt_BR.po
=> pt_BR ready to new shortcuts for next/prev session

source/gx/terminix/terminal/terminal.d
Adds the split buttons to the right click popover menu.
=> Add split buttons to popover menu

po/pt_BR.po
=> Shortcuts translations - pt_BR

po/pt_BR.po
=> pt_BR translations - 100%

data/appdata/com.gexperts.Terminix.appdata.xml.in, extract-strings.sh, install.sh
This lets gnome-software and similar installers present
Terminix nicely.
=> Add appdata

source/gx/terminix/preferences.d
=> Do not remove default profile when adding new one

data/resources/ui/shortcuts.ui, po/bg.po, po/de.po, po/en.po, po/es.po, po/fr.po, po/id.po, po/it.po, po/ko.po, po/pl.po, po/pt_BR.po, po/ru.po, po/terminix.pot, po/zh_CN.po, po/zh_TW.po
This is in addition to #313, I missed that two strings in shortcuts.ui had not yet the context set. I have also updated the po files to reflect the changes.
=> Fixed shortcut localization context

configure.ac, po/LINGUAS
Just a small maintenance commit.
=> autotools: Bump version and add sv to LINGUAS

README.md
I think it's good to show the status of build on the readme; if you don't think the same, feel free to close this :+1:
=> add travis status

data/pkg/desktop/com.gexperts.Terminix.desktop.in, po/ru.po, po/terminix.pot
=> Add action shortcut "New Terminal" and Update Russian localization

README.md
AOSC OS is shipping AOSC OS in its community repository!
=> README.md: AOSC OS is shipping Terminix

dub.json
just saw that - there are probably more places ;-)
=> update copyright to 2016

source/gx/terminix/profilewindow.d
Make sure the window can automatically break the text so it adapts well to different translations.
=> i18n: Localize the profile switch description.

source/gx/terminix/application.d, source/gx/terminix/appwindow.d, source/gx/terminix/cmdparams.d, source/gx/terminix/preferences.d, source/gx/terminix/session.d, source/gx/terminix/terminal/terminal.d, source/gx/util/array.d
This allows building Terminix on x86 and various ARM architectures.
I just verified that the build works properly, there might be issues at runtime that this patch doesn't cover (although it's not likely).
This should also resolve #110 properly.
=> Fix build on 32bit architectures

source/gx/terminix/profilewindow.d
Another typo fix - Lintian is really pedantic with these ^^
=> trivial: Small typo fix

source/gx/terminix/terminal/terminal.d
=> Focus terminal on middle click paste

data/schemes/material.json
Just adding a Material Design inspired theme
=> add new material theme/scheme

source/gx/terminix/appwindow.d
This implements #448.  Simple enough but I get they you may not want to merge it based on what you said in the original issue.
=> Change sessions by scrolling on sidebar button

source/gx/terminix/appwindow.d
Fixes #329 for now until you decide to rework the sidebar.
=> Hide sidebar if open on new session creation

source/gx/terminix/application.d, source/gx/terminix/appwindow.d, source/gx/terminix/cmdparams.d
=> Add minimize command parameter

source/gx/terminix/sessionswitcher.d
Fixes mouse clicks within the switcher window.
=> Fix mouse clicks in session switcher

source/gx/terminix/terminal/terminal.d
We apply this patch at Debian to make builds on ppc64el work again.
=> Fix build on ppc64el

configure.ac
=> Don't override DCFLAGS

data/resources/css/terminix.base.css, source/gx/terminix/terminal/terminal.d
=> Improve terminal titlebar style

source/gx/terminix/appwindow.d, source/gx/terminix/common.d, source/gx/terminix/terminal/terminal.d
=> Convert Find button to ToggleButton so it shows its state

source/gx/terminix/application.d, source/gx/terminix/prefeditor/prefdialog.d, source/gx/terminix/terminal/actions.d, source/gx/terminix/terminal/terminal.d
=> Add "Edit Encodings" item to terminal menu

source/gx/terminix/prefeditor/prefdialog.d
=> gray out shortcuts lists

dub.json
=> Build debug builds with GC flag

po/cs.po
Fixed the weblate merge conflict locally
=> Fix weblate conflict

source/gx/terminix/bookmark/bmeditor.d
=> Fixed saving a path bookmark.

source/gx/terminix/customtitle.d, source/gx/terminix/terminal/terminal.d
=> Fix FTBFS on ppc64el

Makefile.am, configure.ac
=> Fix autotools migration to Tilix

experimental/meson/data/icons/meson.build, experimental/meson/meson.build
Does the project rename in the Meson build files and fixes a few issues.
Looks like your unittests are broken at time, which is why they are commented out in the Meson file at the moment.
=> Fix & adjust Meson build definition

source/gx/tilix/terminal/password.d
Horizontally align the labels on the end
=> Follow GNOME HIG on add/modify password dialog

README.md
Resolves Issue #1018 according to comment https://github.com/gnunn1/tilix/issues/1018#issuecomment-315646510
=> update README.md with instructions for custom directory installations

data/appdata/com.gexperts.Tilix.appdata.xml.in
This PR updates the default screenshot and adds two others from Tilix web repository
=> Fixes #1044

CREDITS.md, README.md, data/scripts/tilix_int.sh, install.sh, source/gx/tilix/colorschemes.d, source/gx/tilix/terminal/password.d
Hi,
Just a small PR in which I have removed old remaining "Terminix" strings.
I haven't touch to Flatpack files as some links probably need to be updated before.
=> removed unneeded terminix entries

source/gx/tilix/customtitle.d, source/gx/tilix/terminal/terminal.d
sorry for claiming that it didn't work. I didn't understand that application title and terminal title are two different things as I have always hidden terminal titlebar.
P.S: I have noticed another segmentation fault after adding a new variable to the terminal title if at least one variable exists. I don't know to trace it.
=> additional fix for #937

source/gx/tilix/terminal/activeprocess.d, source/gx/tilix/terminal/monitor.d, source/gx/tilix/terminal/terminal.d
~It is not efficient but I am comfortable with it.~
~Not sure, how to handle `MonitorEventType`.~
~https://github.com/s4n-gt/tilix/blob/f91c70f5f3e7bae2fddea899e49f19d400ee5eb1/source/gx/tilix/terminal/monitor.d#L140-L146~
please let me know if it needs more comments on the code.
(It is my second D PR, so, I am happy to accept any negative or positive comment.)
(I won't mind if it takes some time before you have enough time to review it)
=> additional support for active process #937

source/gx/gtk/vte.d, source/gx/tilix/constants.d, source/gx/tilix/prefeditor/profileeditor.d, source/gx/tilix/terminal/regex.d, source/gx/tilix/terminal/search.d, source/gx/tilix/terminal/terminal.d
Moves all of the version checks to constants for consistency and makes it easier to patch to compile on Ubuntu 17.10.
=> Consolidate VTE version checks

data/nautilus/open-tilix.py
Fixes the nautilus-python issue. Tried it on my machine and works correctly 
Fixes https://github.com/gnunn1/tilix/issues/1252
=> Fix import error on python3

data/nautilus/open-tilix.py
=> Revert "Fixes #1458"

data/dbus/com.gexperts.Tilix.service, data/dbus/com.gexperts.Tilix.service.in, data/meson.build
This is the latest missing piece to make the meson build system switch working perfectly!
The tests stuff could be handled later
=> configure dbus service file

data/appdata/com.gexperts.Tilix.appdata.xml.in
Per the specs
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html
=> Improve the appdata file

data/pkg/desktop/com.gexperts.Tilix.desktop.in
=> Add a preferences action to the desktop file

data/schemes/yaru.json
Add Yaru (Ubuntu) color scheme
See issue here: https://github.com/ubuntu/yaru/issues/1270
=> Add Yaru scheme

README.md
Given the many requests for tabs in #114, seems worth mentioning tabs.
=> Mention tabs

meson.build
This is optionally loaded with Linker.loadLibrary.
=> meson: add optional libsecret

data/pkg/desktop/com.gexperts.Tilix.desktop.in
This PR just updates spelling for the GNOME project.
=> Change Gnome to GNOME

data/nautilus/open-tilix.py
=> escape nautilus path
