- install.sh
With this patch one can specify an install prefix for installation like so:
```
./install.sh /usr/local
```
I have kept the default as `/usr`, but I actually think it should be changed to `/usr/local` as this is the common location for side installing software (and `/usr` is reserved for distribution packages).
This would also make it easier to build source packages as one can specify a completely different package root (e.g. `${pkgdir}` inside a PKGBUILD). But this is currently prevented by the root check. Not sure, I personally would just remove it. Or we only enable the check when the prefix is `/usr/...`.
> Allow setting an install prefix

- data/nautilus/open-terminix.py
- po/pt_BR.po
- po/terminix.pot
Hello, I took the liberty to add localization support in the nautilus extension (`open-terminix.py`) by using the `gettext` module. I used the same domain as the application to make it simpler, so I added 4 new keys to `terminix.pot`. Then I updated the pt_BR localization with the new keys.
> Prepare nautilus extension for localization

- po/de.po
This adds a nearly complete German translation. No translated are the shortcut actions. Not sure how the other translations handled those, I will take a look.
I tried to follow the guidelines of the German Gnome localization team as close as possible and used a translation memory of the existing Gnome translations to ensure consistency with the rest of the system.
I will try to keep the translation up to date with future changes.
> Nearly complete German translation.

- install.sh
I've made some changes to `install.sh` so that it works with `dash`, as a way to fix #112. I removed the `export -f` bashism and moved the po compilation commands to a `for` loop. I've also added a shebang pointing to `sh`. I've tested it with both `bash` and `dash` and it seems to work.
> Improve install.sh portability

- source/gx/terminix/terminal/layout.d
This change will make the description text wrap automatically depending on the dialog size. Without this change the text might get very long in some languages, stretching the dialog in an ugly way. The manual line breaks workaround isn't that pretty since it will not work well with different font sizes and manually resizing the dialog.
> Automatically wrap the info text in layout options dialog

- data/gsettings/com.gexperts.Terminix.gschema.xml
- source/gx/terminix/appwindow.d
- source/gx/terminix/session.d
Implements #136. This adds directional terminal switching using Alt+Up/Down/Left/Right.
The "next" terminal is determined by moving from the top left coordinates of the currently focused terminal rather than the position of the cursor.
> Add directional terminal switching

- source/gx/gtk/actions.d
- source/gx/terminix/prefwindow.d
This fixes actually two issues:
1. When using Terminix with a non English locale, the localized string for "disabled" got saved to the preferences. This lead to errors while loading the preferences. This PR fixes this by not localizing the value actually saved.  Introduced by myself in bd75e68db72cdd5864b13923db1de2815e114e33, sorry for that.
2. The disabled string was not displayed anymore.
> Fixed shortcut pref disabled string

- data/resources/css/terminix.adwaita.css
- source/gx/terminix/sidebar.d
As of the current master branch the sidebar background on Ubuntu 16.04 is transparent:
This pull request adds a background colour to the sidebar.
> Fix sidebar transparent background

- po/de.po
I am not entirely sure about the shortcuts help window, but I can't yet test it. I will update the translations if necessary once Gnome 3.20 hits Arch.
> Updated German translation for new strings

- source/gx/terminix/application.d
- source/gx/terminix/constants.d
This makes the relevant texts in the about dialog translatable. I haven't run extract-strings in this branch, I suggest doing that after the merge (and after the open translation PRs are merged, too) to avoid conflicts.
> i18n: Localize the about dialog.

- uninstall.sh
This fixes the issue that the schema would remain on the system even though the XML was removed. A wrong / outdated schema present in e.g. /usr/local can make the app crash on start.
> Recompile schema when uninstalling

- data/resources/ui/shortcuts.ui
This makes the section titles in the shortcut overview translatable (the dropdown in the header bar).
To actually take effect this requires an update of the pot/po files.
> Shortcuts help: Mark section titles as translatable.

- data/nautilus/open-terminix.py
- extract-strings.sh
- po/de.po
- po/en.po
- po/fr.po
- po/ko.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/terminix.pot
- po/zh_CN.po
- po/zh_TW.po
This fixes two issues with the localization and updates the strings.
* Nautilus extension localization was broken since c1250367426efa4ae7e05169af220d5a1496db41
* When extracting the strings the last command should all the final options like package name
> I18n fixes: Nautilus extension and extraction order

- source/gx/terminix/application.d
Previously it was just setting the widget name
> Fixed setting the app name in about dialog.

- install.sh
On Ubuntu `/bin/sh` is a symlink to the `dash` shell.  `dash` doesn't like the `==` comparison, it results in
```sh
./install.sh: 79: [: /usr: unexpected operator
```
> Fix install script for dash shell

- install.sh
The current installer copies the terminix appdata file to a file named appdata. Fixed creating appdata folder prior to that.
> Create appdata folder in install.sh

- source/gx/terminix/session.d
Focuses the previously focused terminal, if there is one, when the current terminal is closed.  This only goes one step back and doesn't keep a list of previously focused terminals so sequentially closing terminals will first focus the previous terminal, then go from `n` down to 1 where `n` is the number of terminals.
This also renames `lastFocused` to `currentTerminal` as I thought that it worked better alongside `previousTerminal`.
Fixes #266
> Focus previous terminal on terminal close

- data/pkg/desktop/com.gexperts.Terminix.desktop.in
The choice of categories was not adhering to https://freedesktop.org/wiki/Specifications/menu-spec/ which is punished by a failing build in @openSUSE. This should fix it.
> Fixed the .desktop categories

- extract-strings.sh
- source/gx/i18n/l10n.d
- source/gx/terminix/constants.d
- source/gx/terminix/prefwindow.d
This fixes the shortcut labels to be localized with the proper localization context defined inside `shortcuts.ui` and finalizes the changes introduced for #301 .
Another solution could have been to remove the localization context, but I saw that some of the strings are also used as menu labels, and it is actually useful to be able to have a different (maybe longer) translation in the help text. So I opted for keeping the context but make sure it gets used.
I named the function `C_()` to follow the naming of the C macro commonly used for this.
On a side note the file saving workaround in `l10n.d`can probably be removed. Since it is only used in `_()` and not in the `N_()` and now `C_()` functions it isn't working properly anyway.
> Fix reading the shortcut localization with correct context.

- source/gx/terminix/appwindow.d
- source/gx/terminix/terminal/terminal.d
Gtk-D will otherwise use hardcoded defaults that are not translated, see https://github.com/gtkd-developers/GtkD/blob/master/src/gtk/FileChooserDialog.d
> Localize buttons in FileChooserDialog

- source/gx/terminix/terminal/terminal.d
Adds `${columns}` and `${rows}` as variables for the terminal titles to show the VTE column and row counts.
> Add columns and rows variables for title text

- po/Makevars
Forgot to include it in the previous PR. Does not build without it.
> Include Makevars file to fix building with autotools

- .travis.yml
It's pretty easy to automatically test for various compilers.
See:
https://travis-ci.org/wilzbach/terminix
You need to enable Travis after this is merged.
It's currently failing because of one line
```
source/gx/terminix/prefwindow.d(314): Error: no property 'clear' for type 'string[string]'
```
> add travis support

- po/de.po
For some reason Weblate does not show these strings as fuzzy and does not allow to change it. I tried fixing this in Weblate by pulling and rebasing, but something is broken, so fixing manually.
> i18n: Removed fuzzy marker from German translation

- data/appdata/Makefile.am
- data/appdata/com.gexperts.Terminix.appdata.xml.in
- install.sh
Adds more metadata and removes superfluous or outdated attributes/paths.
This kills some hints from the AppStream metadata generator. Please note that changing the install directory requires up-to-date AppStream tools.
At time, the current (development) releases of all major distributions support this, including Arch, Debian, Ubuntu, Fedora, OpenSUSE. Changing the path might affect backports for some distros (Debian, Ubuntu and Arch are safe, so is OpenSUSE, I am not 100% sure about Fedora).
See https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps for more information on how to write good metainfo files for apps.
> Improve metainfo file

- configure.ac
> Fix configure.ac compiler detection instruction

- data/icons/Makefile.am
SVG icon was being left out here too.
> autotools: install all files under icons/hicolor

- README.md
Since Debian and its derivatives have Terminix now, update their status in the list.
For Ubuntu, point to the build status (it's waiting on LDC at time).
> Update packaging information for Debian

- source/gx/terminix/terminal/terminal.d
`create()` will throw an error if the file already exists.  `replace()` will overwrite the file, or create it if it doesn't already exist.
Fixes #417
> Overwrite file on save, fixes #417

- data/pkg/desktop/com.gexperts.Terminix.desktop.in
Fixes the following errors when running the installer:
```
/usr/share/applications/com.gexperts.Terminix.desktop: error: value "new-window;new-session" for string list key "Actions" in group "Desktop Entry" does not have a semicolon (';') as trailing character
/usr/share/applications/com.gexperts.Terminix.desktop: error: action group "Desktop Action new-window" exists, but there is no matching action "new-window"
/usr/share/applications/com.gexperts.Terminix.desktop: error: action group "Desktop Action new-session" exists, but there is no matching action "new-session"
```
> Add semi colon to Actions attribute in .desktop

- data/icons/meson.build
- meson.build
- po/meson.build
Hi!
I am not sure if you actually want this patch, because Terminix has two build systems already, but since I wrote it already, making a PR out of it and ask for feedback won't hurt.
So, what is Meson and why should you use it?
Meson is a fast, Ninja-based buildsystem where I recently added D support to (currently under review at https://github.com/mesonbuild/meson/pull/685). It is much more powerful than dub and also compiles much faster than dub.
In spirit, it is comparable to CMake/Autotools, but without all the craziness and following a very clean and simple design.
See https://ninja-build.org/ for information on Ninja (which also compiles stuff like e.g. Google Chrome) and http://mesonbuild.com/ for Meson.
To give a few numbers, a compilation of Terminix using dub takes about 8.6s …
> Add support for building with Meson

- data/gsettings/com.gexperts.Terminix.gschema.xml
- source/gx/terminix/appwindow.d
- source/gx/terminix/preferences.d
- source/gx/terminix/prefwindow.d
Inspired by an option in Firefox to not close the window when the last tab is closed, I've added the same functionality to terminix.  Quite often I'll hit `Ctrl+d` quickly to close terminals and end up closing terminix.
The default is to close the window so it acts in the same way it previously did, but turned off the option will open a new session in the window when the last session is removed.
The window can still be closed by pressing the close icon in the header bar.
> Add option to not close window with last session

- install.sh
Using plain `cp` and `mkdir` will fail when using a non-standard umask
for either compiling Terminix or running the installation script. Fix that
by using the `install` command with explicit modes when necessary.
Additionally, ensure the desktop file cache and icon cache are properly
updated when either /usr or /usr/share is chosen as PREFIX.
> Make install script more robust

- Makefile.am
- configure.ac
I've used the pkg-config tooling to look for libx11 and added a corresponding linker flag. Works for me. More testing (especially cross-distro) appreciated.
> autotools: check for and link with libx11

- data/appdata/com.gexperts.Terminix.appdata.xml.in
The file contained some non-visible characters, and some more strict XML parsers choke on that.
> trivial: Remove invalid chars from metainfo file

- extract-strings.sh
- po/bg.po
- po/cs.po
- po/de.po
- po/el.po
- po/en.po
- po/es.po
- po/fr.po
- po/he.po
- po/id.po
- po/it.po
- po/ko.po
- po/lt.po
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/sv.po
- po/terminix.pot
- po/tr.po
- po/uk.po
- po/zh_CN.po
- po/zh_TW.po
Now extract-strings.sh updates the pot file so it will contain only existing strings.
> i18n: Obsolete strings were not automatically removed

- configure.ac
When downloading dmd for Debian from [here](https://dlang.org/download.html#dmd), the .deb install a binary called `/usr/bin/ldmd2` (instead of the expected `ldmd`).
> ldmd2 is another name for ldmd on Debian

- Makefile.am
As per https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842629
Btw, finding the source files that way is pretty bad... It's a hack to not make you deal with Automake much, but not a very good solution to this problem.
> Make build reproducible

- source/gx/terminix/terminal/exvte.d
```
source/gx/terminix/terminal/exvte.d(90): Error: cannot implicitly convert expression (this.onNotificationReceivedListeners[this.onNotificationReceivedListeners.length - 1u].handlerId) of type ulong to uint
source/gx/terminix/terminal/exvte.d(141): Error: cannot implicitly convert expression (this.onTerminalScreenChangedListeners[this.onTerminalScreenChangedListeners.length - 1u].handlerId) of type ulong to uint
```
> Fix build errors

- data/scripts/terminix_int.sh
This bash script is missing a shebang and is getting a warning from rpmlint report when build terminix as rpm package on OBS (http://build.opensuse.org).
> rpmlint warning for missing shebang

- data/gsettings/com.gexperts.Terminix.gschema.xml
- data/nautilus/open-terminix.py
- data/resources/ui/shortcuts.ui
- source/gx/terminix/prefeditor/prefdialog.d
Some code of the extension was still using Python2, modified that. Fixed some stuff and imported only needed libraries/functions.
The current shortcut is CTRL + Z
I opened this PR in order to see if it's possible to add a new configuration for that in Terminix itself, so I can change that to use the configured shortcut from DConf directly.  Or just if anyone has a better proposal 
Here's a small video that shows how it works
https://youtu.be/Sxi_8UggqGY
PS: works only with directories. FTP and SFTP are not supported (maybe it's possible) i will try to investigate more and push a fix in the future!
> Add Nautilus shortcut, fixes #672

- source/gx/terminix/session.d
> When saving a session, use C locale to make sure session file will be correct

- data/resources/ui/shortcuts.ui
I guess this could be the reason why "Terminal" is not translated under Preferences -> Shortcuts.
> Add missing context field

- install.sh
To avoid damaged installations in case a command is missing.
> Check availability of required commands in install script

- data/man/po/de.man.po
- data/man/po/terminix.man.pot
- extract-strings.sh
- install.sh
- uninstall.sh
Fixes #713 
This enables translation of manpages using po4a. [po4a](https://po4a.alioth.debian.org/) is required, however without po4a the install scripts will still work, it will just ignore manpage localization.
The process is as follows:
1. On changes to the manpage `extract-strings.sh` should be run. This was extended to also update the manpage translation template and translations in `data/man/po`
2. To translate into a new language just use `data/man/po/terminix.man.pot` to create a new PO file, name it `data/man/po/[locale].man.pot` (a German translation is included here as an example)
3. On installation `install.sh` will use the translations to place translated manpages in `share/man/[locale]/man1`
Once this is merged we should see to get this into Weblate also. I think we will …
> Allow localizing manpages

- extract-strings.sh
- po/bg.po
- po/cs.po
- po/de.po
- po/el.po
- po/en.po
- po/es.po
- po/fr.po
- po/he.po
- po/id.po
- po/it.po
- po/ja.po
- po/ko.po
- po/lt.po
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/pt_PT.po
- po/ru.po
- po/sv.po
- po/terminix.pot
- po/tr.po
- po/uk.po
- po/zh_CN.po
- po/zh_TW.po
- source/gx/terminix/application.d
- source/gx/terminix/constants.d
Instead of a static string this uses the customary msgid “translator-credits” for the translator credts in the about dialog, as recommended at https://developer.gnome.org/gtk3/stable/GtkAboutDialog.html#gtk-about-dialog-set-translator-credits . This allows each translator to add himself to the credits, also makes the credits for the actual translation.
I have also updated the language files and added the existing contributors to the credits as they were credited in the PO files or commits already.
> Translator credits

- source/gx/terminix/prefeditor/prefdialog.d
fixes #756 
On other Widgets
@gnunn1 I would like to add a CTRL + F to reveal the search entry, but as it's my first attempt to write D code, some tips would be very helpfull :)
> hide searchentry by default

- data/nautilus/open-terminix.py
This fix removes a condition that I've added in my latest commit to checking if Terminix is installed in the system or not.
Anyway, this fix it and I've also introduced a small condition to verify whether the GSettings are correctly found to avoid crashing Nautilus!
> Fixes #797

- .gitignore
- Makefile.am
- configure.ac
- data/man/Makefile.am
This adds a new build dependency for autotools builds (`po4a-translate`), required for localizing man pages.
EDIT: Works For Me, so more testing would be nice.
EDIT2: This should fix #842
> autotools: improve man page installation, generate localized man pages

- data/nautilus/open-tilix.py
g_file_query_info is a sync API that will do IO and potentially
block if the network connection is slow (or dropped). If that
call blocks, it will freeze nautilus since the extension is called
from the main thread. Since we only use the resulting information
for the filename add a tooltip use the get_name() provided by
nautilus itself instead.
> Don't call query_info which might block

- Makefile.am
Every linker flag for libx11 needs to be preceded with `-L` . However, only the first flag was actually done so, causing build failures when pkg-config returned multiple linker flags for libx11.
```
make[1]: Entering directory '/tmp/nix-build-tilix-1.5.6.drv-0/tilix-1.5.6'
/nix/store/jzv9nh5k5pmcimmmlyk3grcjklbkimwx-dmd-2.070.2/bin/dmd -O -I/nix/store/5lrssnllkm9c89wbx5k8xw51ilrsrhnl-gtkd-3.6.1/include/d/gtkd-3/ -L-lvted-3 -L-L/nix/store/5lrssnllkm9c89wbx5k8xw51ilrsrhnl-gtkd-3.6.1/lib// -L-lgtkd-3 -L-ldl -c source/app.d source/gx/gtk/actions.d source/gx/gtk/cairo.d source/gx/gtk/clipboard.d source/gx/gtk/dialog.d source/gx/gtk/resource.d source/gx/gtk/settings.d source/gx/gtk/threads.d source/gx/gtk/util.d source/gx/gtk/vte.d source/gx/gtk/x11.d source/gx/i18n/l10n.d …
```
> Fix linker flags

- source/gx/tilix/customtitle.d
I've fixed both issues I mentioned in #945. I also moved some code that does not need to be set for each mode. Only setting hexpand for the stack is enough.
> Fix headerbar title centralization (#945)

- configure.ac
The configure.ac sets DCFLAGS, which means that it's not possible to set custom DCFLAGS when building the program.  This changes configure.ac so that it will only set default DCFLAGS if it has not already been set externally.
Tilix in Debian was accidentally built with debugging enabled because of this.  See https://bugs.debian.org/863491.
> autotools: Don't override DCFLAGS

- data/nautilus/open-tilix.py
Just making the extension code more pythonic 
- Sort imports and remove unneeded ones
- Make use of some constants (easier to modify later)
- `file` shouldn't be used as a variable name
-  respect PEP8 a little bit more (not perfect due to `require_version`)
- Removed a print that was sending an unneeded output for each action you do on Nautilus (doesn't affect the user at all, but as I usually modify/create Nautilus stuff it just shows a lot of outputs for no reason....)
> Clean the open-tilix.py code

- data/nautilus/open-tilix.py
Fixes #965
See also http://python-gtk-3-tutorial.readthedocs.io/en/latest/unicode.html on details on pygtk encoding handling. The string object is guaranteed to use utf-8 encoding, so the decode is fine.
> Fix Nautilus decode unicode error

- data/scripts/tilix_int.sh
On Debian the HOSTNAME variable wasn't define, using a call the the hostname bin populate it.
> Define the HOSTNAME Variable in tilix_int.sh

- source/gx/tilix/appwindow.d
- source/gx/tilix/constants.d
I use this patch to show the total session number in the application title. A usecase is having the current session / total session, for example 1/2 :
> [RFC] add total number of sessions in application title

- source/gx/tilix/appwindow.d
- source/gx/tilix/terminal/exvte.d
- source/gx/tilix/terminal/terminal.d
- ~~Do not crash when opening window (it still sometimes crash when closing window)~~
- Keep stdio usable
- Use env vars from host, so that more commands work (for example `flatpak remote-list`)
Issue #582
> Fix Flatpak build

- experimental/flatpak/com.gexperts.Tilix.json
- source/gx/tilix/terminal/terminal.d
- Share pseudoterminal devices with host (and every other device)
- Do not overwrite TERM and VTE_VERSION env vars.
> Flatpak improvements

- README.md
In https://github.com/gnunn1/tilix/issues/1168#issuecomment-340264899 gnunn1 said:
> LDC is supported, it says not supported somewhere then that should be corrected. It's GDC that's not supported.
This PR clarifies the compiler support in the README to match this.
> Clarify compiler support in README

- source/gx/gtk/x11.d
This PR fixes the extern declarations of x11 functions from the gdk library.
The function symbols in `__gshared extern(C)` were compiled as global function pointers initialized to zero, which caused the relocation table in `libgtk-3.so.0` to contain invalid entries for these particular functions.
This is fixed by prepending a prefix to avoid a name clash and introducing an alias (just like in the gtkd library).
> Fix crashes caused by x11 gdk extern declarations

- data/scripts/tilix_int.sh
Use `TILIX_SILENT=1 source /path/to/tilix_int.sh` in the .bashrc / .zshrc / ... to hide the message.
> Add a way to silence `Adding tilix osc7` message

- source/gx/tilix/terminal/activeprocess.d
source/gx/tilix/terminal/activeprocess.d(43): Error: cannot implicitly convert expression (rpar) of type long to uint
source/gx/tilix/terminal/activeprocess.d(44): Error: cannot implicitly convert expression (rpar + 2L) of type long to uint
> Fix the build on 32 bit arches

- Makefile.am
This fixes so Tilix can run on Archlinux again.
Without this Tilix will always link to the staticlibs of druntime/phobos, due to it ignoring the DCFLAGS.
The Arch package also requires this patch:
```patch
From 4f0f7eb8211a83d57d89a5aeb0211c47f9ae1baf Mon Sep 17 00:00:00 2001
From: Dan Printzell <xwildn00bx@gmail.com>
Date: Mon, 8 Jan 2018 15:03:02 +0100
Subject: [PATCH] Link to the shared version of druntime&phobos
Signed-off-by: Dan Printzell <xwildn00bx@gmail.com>
---
PKGBUILD | 4 ++--
1 file changed, 2 insertions(+), 2 deletions(-)
diff --git a/PKGBUILD b/PKGBUILD
index b4ee388..8d0b421 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -30,8 +30,8 @@ prepare() {
build() {
cd "$pkgname-$pkgver"
-    ./configure --prefix=/usr PO4A_TRANS=/usr/bin/vendor_perl/po4a-translate
-    make DC='ldmd' …
```
> Add DCFLAGS to linking, fixes #1243

- source/gx/tilix/prefeditor/profileeditor.d
Some text strings in ProfileEditor stand out by using CamelCase notation. Propose to make them look like other strings that have only one capital letter.
> Normalize text strings in ProfileEditor

- source/gx/tilix/terminal/activeprocess.d
sometimes, after running for a while, active process name doesn't change and new terminal shows 'unknown' active process until a restart. 
I am using this fix for some time and I haven't noticed the problem again.
> activeprocess.d: fix unknown active process issue

- source/gx/tilix/terminal/advpaste.d
This fixs paste trasnform function.
Its motto is replaceing CRLF & CR to LF but it replace '/r/n' & '/r' -> '/n'.
So Fix ' / ' -> ' \ '.
> Fix transform func misstyping '/' -> '\'

- data/resources/css/tilix.base.css
Simplifies keyboard navigation in the Bookmarks view . This fixes my main annoiance whith tilix right now.
I thought about limiting this to bookmarks view only, but it kind of makes sense to have this consistent with other places, e.g. the key binding tree view.
> Set right / left arrow keys to expand / collapse tree views

- extract-strings.sh
`po4a-updatepo` does not accept multiple output files provided with a single `-p` option.
Update the script to call `po4a-updatepo` per each translation file.
> Fix manpage translations update

- data/man/tilix
Remove '+' chars; add a '\\' to `\-\-window\-style`.
> Man page: Clean up merge artifacts

- data/gsettings/com.gexperts.Tilix.gschema.xml
- data/resources/ui/shortcuts.ui
- source/gx/tilix/appwindow.d
- source/gx/tilix/session.d
Hello,
I came across this awesome project a couple of weeks ago and have been using this terminal emulator since then. So first of all thank you for developing and maintaining this great project!
Before using Tilix in GNOME I was using i3wm and I really liked the "auto-tiling" feature that allowed me to split screens vertically and horizontally with one key binding (mod + Enter). So I implemented it also for my new favorite terminal emulator.
This PR adds a new key to split a terminal depending on the current height and width.
Here's the result:
Here I pressed the "auto-tiling" key three times.
I would be glad to get some feedback on this PR and maybe see this feature implemented in the next
version of Tilix!
> Add auto-oriented splitting (Request for feedback from community)

- data/nautilus/open-tilix.py
The issue was due to 
```python
value = '{0} cd "{1}" ; $SHELL'.format(value, result.path)
```
The value of `result.path` is now passed to `unquote` function before. And the spaces also have a \ before so it works correctly on the terminal.
Tried that on my personal FTP server and everything works correctly.
> Fixes #1458

- source/gx/tilix/preferences.d
Currently the rule `:~/myfolder` will match both `~/myfolder/` and `~/myfolderwithextrachars/`
This solution compares folder by folder if the path matches
> Path matching for auto profile switching

- source/gx/tilix/appwindow.d
This matches the convention shown in
https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement
> Rename Shortcuts menu item to Keyboard Shortcuts

- experimental/flatpak/com.gexperts.Tilix.yaml
- Update the runtime to the latest one
- Remove uneeded tags
- Build flatpak from git instead of the directory. 
- Use meson build system
> Update flatpak manifest

- source/gx/tilix/terminal/terminal.d
See https://twitter.com/BabyWogue/status/1075527836612612096
Before the patch, the app crashes on Wayland/X11
```
(tilix:7412): Gdk-CRITICAL **: 00:22:11.876: gdkdisplay-wayland.c:1402: Unable to create Cairo image surface: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
fish: “tilix” terminated by signal SIGSEGV (Address boundary error)
```
Results after the patch
Doesn't happen anymore on Wayland.
> UnsafePasteDialog: Make sure pasted command fits on the prompt

- data/nautilus/open-tilix.py
The Nautilus extension has an issue in Python 3, in which the strings handled in `get_file_items` are already unicode strings, and so throw an error if `.decode()` is called on them. This PR only decodes them if they are bytestrings, otherwise it leaves them as-is. With this change, the extension doesn't throw any errors (and appears to work, importantly!) when using a version of nautilus-python that is compiled with Python 3.
In addition, two debug printlines are removed in this PR, resolving issue #1609.
> Nautilus extension: do not decode already-decoded strings, remove debug printines

- source/gx/tilix/sidebar.d
Correctly use gulong instead of size_t as per
https://developer.gnome.org/gobject/stable/gobject-Signals.html
This fixes the build on aarch64.
> Fix signal handler id data type

- data/meson.build
Currently, we validate the appata file using appstream-util which requires network access to fetch the screenshots and validate them. 
A lot of distros out there run tests without network access, this will make the appdata test fail and they might patch Tilix downstream.
> Meson: validate appdata without network access

- source/gx/tilix/application.d
Per the GNOME Design initiative to remove the usage of the in-app menu and replace it with a primary menu in the application itself. We already have everything moved to the primary menu.
Fixes #1629
> gtk: stop setting inApp menu

- data/icons/hicolor/scalable/apps/com.gexperts.Tilix-symbolic.svg
- data/icons/hicolor/scalable/apps/com.gexperts.Tilix.svg
The most recent icon guidelines recommend bottom-aligning wide shapes.
This PR fixes the alignment and also makes the icon a bit more distinct from GNOME Terminal by adding a second split, and a more unique symbolic.
> App icon: update to most recent GNOME guidelines

- source/gx/tilix/application.d
When runninf `tilix --help` the documentation for `--group` did not indicate that there was a reuired parameter:
```
-g, --group             Group tilix instances into different processes (Experimental, not recommended)
```
Now it does:
```
-g, --group=GROUP_NAME             Group tilix instances into different processes (Experimental, not recommended) 
```
> Add GROUP_NAME parameter to the --help output for --group

- source/gx/tilix/terminal/monitor.d
* This fixes a compilation on dmd v2.087.0+ ( I think? )
/usr/include/dmd/druntime/import/object.d(3453,36): Error: cannot implicitly convert expression aa of type shared(ProcessStatus[int]) to const(shared(ProcessStatus)[int])
source/gx/tilix/terminal/monitor.d(46,46): Error: template instance `object.values!(shared(ProcessStatus[int]), shared(ProcessStatus), int)` error instantiating
> Avoid calling `values()` on a shared object

- source/gx/tilix/appwindow.d
Previously the writing to a session file was only done if the Save As dialog was shown.  This PR fixes that and fixes #1718.
> Fixes #1718 - Fix saving of already saved session

- data/gsettings/com.gexperts.Tilix.gschema.xml
When using tab mode it is helpful to distinguish the different tabs properly e.g. by seeing at first glance what user host or directory is actually used on the shell. Using the ${title} variable ensures that you hit the right tab when you have multiple sessions. Without this patch every tab just shows the text 'Default'.
> Gives every tab the ${title}

- configure.ac
When using `./configure DC=gdmd` and `make` it should used gdmd, but if ldmd is installed on system it is used instead.
This should fix it.
> Fix autoconf DC variable

- install.sh
Alternative implementation:
```bash
export PREFIX="${1:-${PREFIX:-/usr}}"
```
This is [portable](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02):
> ${_parameter_:-**[**_word_**]**}
> **Use Default Values**. If _parameter_ is unset or null, the expansion of _word_ (or an empty string if _word_ is omitted) shall be substituted; otherwise, the value of _parameter_ shall be substituted.
For people familiar with this construct the code is much easier to read. It's obvious at the first glance that `$1`, `$PREFIX` and `/usr` are considered in this order.
> bug fix: invert the condition when checking for PREFIX

- data/gsettings/com.gexperts.Tilix.gschema.xml
- data/resources/ui/shortcuts.ui
- source/gx/tilix/terminal/actions.d
- source/gx/tilix/terminal/terminal.d
This adds the option to bind a keyboard shortcut to "Unselect All", fixing #1801.  The state is set to `disabled` by default rather than trying to find an available and appropriate key binding.
This doesn't add a corresponding "Unselect All" option to the context menu which is easy enough to do but I couldn't find an inverse icon for `edit-select-all-symbolic`.
> Add shortcut to "Unselect all"

- data/meson.build
yaru.json is missing from data/meson.build and so it is not istalled.
Closes #1926
> [meson] add yaru scheme to install_data

- install.sh
I was hitting multiple directory creation errors when
attempting to install to a custom `PREFIX` earlier
today.
Upon further investigation, I found that 9347910e broke
the scripts when the `-d` flag for the `install`
command was replaced with the `-D` flag, but without
the right adaptation to the rest of the arguments.
The `install` command was stuck between 2 possible
options that arose from the change in flags.
See 6c1b0076 for more.
> [scripts] fix `install.sh` script for directory errors

- data/scripts/install-man-pages.sh
the man page filename was changed in b3e8718c, but was missed to be
updated in the `install-man-pages.sh` script
> [scripts] fix man page filename in `install-man-pages.sh`

- data/scripts/tilix_int.sh
The function ` __tilix_osc7()` in the `scripts/tilix_int.sh` script overrides the previous command exit code (when calling the`printf` command), so some tools that render custom prompts, like [Bash-it](https://github.com/Bash-it/bash-it), or [Starship](https://github.com/starship/starship) can't show the correct value.
This PR fixes it.
> Avoid messing the previous exit code

- data/gsettings/com.gexperts.Tilix.gschema.xml
- source/gx/tilix/prefeditor/prefdialog.d
- source/gx/tilix/preferences.d
- source/gx/tilix/terminal/terminal.d
> Added an option to strip trailing whitespace on paste

- .gitignore
- install.sh
A follow up to https://github.com/gnunn1/tilix/commit/51d0f8b09a0ec5575bb3d2e58d758a8539c9e549
Building this project without these changes created these error messages:
```plaintext
sudo ./install.sh
.....
Processing po/zh_CN.po
Processing po/zh_TW.po
msgfmt: cannot read data/appdata/com.gexperts.Tilix.appdata.xml.in: failed to load external entity "data/appdata/com.gexperts.Tilix.appdata.xml.in"
msgfmt: cannot read data/appdata/com.gexperts.Tilix.appdata.xml.in: failed to load external entity "data/appdata/com.gexperts.Tilix.appdata.xml.in"
msgfmt: cannot read data/appdata/com.gexperts.Tilix.appdata.xml.in: failed to load external entity "data/appdata/com.gexperts.Tilix.appdata.xml.in"
msgfmt: cannot read data/appdata/com.gexperts.Tilix.appdata.xml.in: failed to load external entity …
```
> more appdata -> metainfo move

- source/gx/gtk/threads.d
- source/gx/tilix/appwindow.d
Simply allow the focusOut timeout (that closes the quake window) to be cancelled and specifically cancel it in the focusIn event handler.
Fixes:
- https://github.com/gnunn1/tilix/issues/1658
- https://github.com/gnunn1/tilix/issues/1647
Relates to:
- https://github.com/gnunn1/tilix/issues/858
> keep quake window open if focus is restored before timeout has been reached

- data/meson.build
See https://github.com/mesonbuild/meson/issues/9441. Fixes https://github.com/gnunn1/tilix/issues/2061. Tested via 1.9.4 [downstream](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260943).
```
$ meson setup _build
[...]
data/meson.build:13:0: ERROR: Function does not take positional arguments.
```
http://www.ipv6proxy.net/go.php?u=http://package18.nyi.freebsd.org/data/122amd64-default-foo/2022-01-20_18h39m40s/logs/errors/tilix-1.9.4.log
> Unbreak build with Meson 0.61.0

- source/gx/tilix/sidebar.d
- source/gx/tilix/terminal/terminal.d
Wayland does not set cancel reason thus this check always fails.
See: https://gitlab.gnome.org/GNOME/gtk/-/issues/2101
> Don't check GtkDragResult

- source/gx/tilix/terminal/terminal.d
When running under Wayland if we add application/x-rootwindow-drop to
dragSourceSet targets then we end up getting spammed with endless calls
onTitleDragDataGet() when we drag and drop title onto root window.
Also it seems like sidebar never added application/x-rootwindow-drop to
its dragSourceSet targets so I suppose this is fine.
This change along with #2062 fixes an issue described here: #1906
> Don't add application/x-rootwindow-drop to dragSourceSet targets

- data/man/meson.build
- data/meson.build
Add a new meson custom which allows to generate and install man page
translations using `meson build` and `meson install` when po4a is
available.
This is a naive conversion of install-man-pages.sh.
> Add meson target for man page translations

- data/gsettings/com.gexperts.Tilix.gschema.xml
- source/gx/tilix/prefeditor/prefdialog.d
- source/gx/tilix/preferences.d
- source/gx/tilix/terminal/search.d
Hello,
When I want to copy something from terminal (like a part of some output) I always use regex in search.
I believe many people also does this.
I thought it'd be really nice to be able to configure regex in search so it's always enabled.
> Add possibility to configure always enabled regex

- data/nautilus/open-tilix.py
Nautilus 43 and nautlius-python 4 introduce major changes to the extension API. (Nautilus 43 also was ported to GTK4.)
The GNOME 43 Release Candidate is being released in the [next few days](https://wiki.gnome.org/FortyThree) and the stable release will happen on September 21.
I guess this merge proposals breaks the keyboard shortcut for Nautilus > Open in Tilix. (By the way, Ubuntu Desktop uses Ctrl+Alt+T for their systemwide Launch a Terminal feature.)
> nautilus: Add compatibility with Nautilus 43

- dub.json
- dub.selections.json
I currently have a problem with building dmd on NixOS, so wasn't able to test it with dmd.
But building with ldc works fine.
The CI/CD should be running, though.
> Update to GtkD 3.10.0

- data/resources/ui/shortcuts.ui
- po/tilix.pot
The previous label ("View configured shortcuts") implied that what would be shown was only the shortcuts that were explicitly configured (by the user), but this is not the case.
The new label ("Show keyboard shortcuts") removes the ambiguity, uses a verb whose actor is the program (in line with the other actions) and explicitly mentions the term keyboard shortcuts, for extra clarity.
> Change label of "view shortcuts" action

- source/gx/tilix/terminal/search.d
This patch add a close button to the search box, adding to pressing `esc` while on the search box input and the toggle button on the Window, to close the Search box area.
Fixes #2131
> Add close button to search box

- data/nautilus/open-tilix.py
I first reported this issue in https://bugs.archlinux.org/task/77698.
Currently tilix's open-tilix plugin for nautilus uses `subprocess.call()` with `shell=True`. However it fails to sanitize input data (filename) correctly, thus causing possible shell injection when filename contains `"` or `` ` ``, etc.
This PR tries to solve this issue by using `subprocess.Popen()` and avoiding invoking shell:
- [`Popen constructor`](https://docs.python.org/3/library/subprocess.html#popen-constructor) recommends to use `shutil.which()` to get actual path of executable (requires Python 3.3+).
- For `REMOTE_URI_SCHEME` part, [subprocess security considerations](https://docs.python.org/3/library/subprocess.html#security-considerations) recommends to use `shlex.quote()` to escape path (also requires Python …
> fix(security): avoid shell injection in open-tilix plugin

- install.sh
Removes a duplicate `glib2` from `$PACKAGES`
> Remove duplicate package in install script
